// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"auth_service/controller"
	"auth_service/service"
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	"net/http"
)

// Injectors from injector.go:

func InitServer() *http.Server {
	authServiceImpl := service.NewAuthServiceImpl()
	authControllerImpl := controller.NewAuthServiceImpl(authServiceImpl)
	router := NewRouter(authControllerImpl)
	server := NewServer(router)
	return server
}

// injector.go:

var ServerSet = wire.NewSet(
	NewRouter,
	NewServer, wire.Bind(new(http.Handler), new(*httprouter.Router)), service.NewAuthServiceImpl, wire.Bind(new(service.AuthService), new(*service.AuthServiceImpl)), controller.NewAuthServiceImpl, wire.Bind(new(controller.AuthController), new(*controller.AuthControllerImpl)),
)
